# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_Lohmann_conv <- function(tmpm) {
    .Call('_XAJ_aux_Lohmann_conv', PACKAGE = 'XAJ', tmpm)
}

XAJrun <- function(PREC, EVAP, parameters, UH) {
    .Call('_XAJ_XAJrun', PACKAGE = 'XAJ', PREC, EVAP, parameters, UH)
}

